### ISSUE TITLE
Reacting with Unicode emoji is broken from 0.37.107

### ISSUE THREAD

**Issue by kevinlul** [discordjs/discord-api-types#1181]
### Issue description

Calling `.react` on a message in Discord.js is working prior to 107 and broken from 107 onward. The Discord endpoint responds with 400, specific error is "Unknown Emoji". I believe is because of escaping that was introduced in this version: https://github.com/discordjs/discord-api-types/releases/tag/0.37.107

Sample error:
```
{
  "requestBody": {},
  "rawError": { "message": "Unknown Emoji", "code": 10014 },
  "code": 10014,
  "status": 400,
  "method": "PUT",
  "url": "[https://discord.com/api/v10/channels/381295433256796162/messages/1320463836716732478/reactions/%F0%9F%95%99/@me"%7D,
  "stack": "DiscordAPIError[10014](https://discord.com/api/v10/channels/381295433256796162/messages/1320463836716732478/reactions/%F0%9F%95%99/@me%22%7D,%22stack%22:%22DiscordAPIError[10014)]: Unknown Emoji\n    at handleErrors (/app/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SequentialHandler.runRequest (/app/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:417:20)\n    at async SequentialHandler.queueRequest (/app/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)\n    at async _REST.request (/app/node_modules/@discordjs/rest/src/lib/REST.ts:210:20)\n    at async GuildMessageManager.react (/app/node_modules/discord.js/src/managers/MessageManager.js:255:5)\n    at async Message.react (/app/node_modules/discord.js/src/structures/Message.js:872:5)\n    at async SearchMessageListener.addReaction (/src/events/message-search.ts:470:11)"
}
```

### Code sample

```typescript
message.react("🕙");
```

### Package version

0.37.107 through 0.37.112

### Runtime

Node.js

### Runtime version

20.17.0

### Priority this issue should have

High (immediate attention needed)

**Comment by vladfrangu** [comment]
That's peculiar, I've tested this before and it worked, its why I did such a blanket handling

**Comment by vladfrangu** [comment]
Fixed in the next release of -types, not sure if you'll just need to nuke lock file or we need to release it on djs side

**Comment by kevinlul** [comment]
I should be able to handle it if it's https://github.com/discordjs/discord-api-types/releases/tag/0.37.113

**Comment by kevinlul** [comment]
Change was not effective:
```
{"message":"Unknown Emoji","code":10014},"code":10014,"status":400,"method":"PUT","url":"https://discord.com/api/v10/channels/1320466398597615666/messages/1320505805178671155/reactions/%25F0%259F%2595%2599/@me"},"stack":"DiscordAPIError[10014]: Unknown Emoji\n    at handleErrors (C:\\Users\\home-dell\\Documents\\Codespace\\bastion-iii\\node_modules\\@discordjs\\rest\\src\\lib\\handlers\\Shared.ts:148:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SequentialHandler.runRequest (C:\\Users\\home-dell\\Documents\\Codespace\\bastion-iii\\node_modules\\@discordjs\\rest\\src\\lib\\handlers\\SequentialHandler.ts:417:20)\n    at async SequentialHandler.queueRequest (C:\\Users\\home-dell\\Documents\\Codespace\\bastion-iii\\node_modules\\@discordjs\\rest\\src\\lib\\handlers\\SequentialHandler.ts:169:11)\n    at async _REST.request (C:\\Users\\home-dell\\Documents\\Codespace\\bastion-iii\\node_modules\\@discordjs\\rest\\src\\lib\\REST.ts:210:20)\n    at async GuildMessageManager.react (C:\\Users\\home-dell\\Documents\\Codespace\\bastion-iii\\node_modules\\discord.js\\src\\managers\\MessageManager.js:255:5)\n    at async Message.react (C:\\Users\\home-dell\\Documents\\Codespace\\bastion-iii\\node_modules\\discord.js\\src\\structures\\Message.js:872:5)\n    at async SearchMessageListener.addReaction (C:\\Users\\home-dell\\Documents\\Codespace\\bastion-iii\\src\\events\\message-search.ts:470:11)"}
```

**Comment by vladfrangu** [comment]
Having done tests, that is impossible. Make sure you've overriden the discord-api-types version properly and that the override did apply! Also please get me a reproduction sample that is directly in -types and not through layers 🙏

**Comment by kevinlul** [comment]
package.json
```json
{
  "dependencies": {
    "discord-api-types": "0.37.113"
  }
}
```
const { Routes } = require('discord-api-types/v10');
console.log(Routes.channelMessageOwnReaction('1320466398597615666', '1320622300642545705', '%F0%9F%95%99'));
console.log(Routes.channelMessageOwnReaction('1320466398597615666', '1320622300642545705', '%F0%9F%95%99'));
console.log(Routes.channelMessageOwnReaction('1320466398597615666', '1320622300642545705', '%F0%9F%95%99'));
console.log(Routes.channelMessageOwnReaction('1320466398597615666', '1320622300642545705', '%F0%9F%95%99'));
```

Output:
```
/channels/1320466398597615666/messages/1320622300642545705/reactions/%F0%9F%95%99/@me
/channels/1320466398597615666/messages/1320622300642545705/reactions/%25F0%259F%2595%2599/@me
/channels/1320466398597615666/messages/1320622300642545705/reactions/%F0%9F%95%99/@me
/channels/1320466398597615666/messages/1320622300642545705/reactions/%25F0%259F%2595%2599/@me
```

Was losing my mind debugging this as the behaviour changed when I added logging, until I noticed this flip-flopping behaviour.

**Comment by vladfrangu** [comment]
What the everloving fuck. Ok, I think I know the culprit and will release a fix rn

**Comment by kevinlul** [comment]
Thanks for responding and fixing so quickly!
