### ISSUE TITLE
`APIInteractionDataResolvedChannel` missing thread-specific data

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord-api-types#187]
**Please describe the problem you are having in as much detail as possible:**
The type in question:
https://github.com/discordjs/discord-api-types/blob/b6babf2ee2c66817ac99752d14feed2d574ecb14/payloads/v9/_interactions/applicationCommands.ts#L83-L85

I noticed that from discordjs/discord.js/pull/6521, thread channels returned the following (example) payload:
```TypeScript
{
  '879342171570978847': {
    type: 11,
    thread_metadata: {
      locked: false,
      auto_archive_duration: 1440,
      archived: false,
      archive_timestamp: '2021-08-24T23:08:09.721000+00:00'
    },
    permissions: '549755813887',
    parent_id: '846428632897290260',
    name: 'hi',
    id: '879342171570978847'
  }
}
```

As you can see, there is more than `id`, `name`, `type` & `permissions` here! `parent_id` and `thread_metadata` are also included.

**Further details:**

- Node.js version: 16.6.1
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Comment by advaith1** [comment]
update details:

* https://github.com/discord/discord-api-docs/discussions/3547#discussioncomment-1125302 
* https://github.com/discord/discord-api-docs/commit/73b9aae8a1a5bbf3a54b29588284f3dd57787b69
