### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in package.json

### ISSUE THREAD

**Issue by norilux** [discordjs/discord-api-types#206]
After installing got issue "Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in"

**Further details:**

- Runtime:
  
  - Node.js version: 16.10.0
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by vladfrangu** [comment]
Not sn error, your imports must be versioned
