### ISSUE TITLE
Options in Select Menus are marked as optional when they're not

### ISSUE THREAD

**Issue by PikaDude** [discordjs/discord-api-types#247]
**Please describe the problem you are having in as much detail as possible:**
According to the following line, `options` is marked as an optional property in Select Menu components. However, this is not the case, and the API will return it as a bad request if you attempt to omit the `options` property when sending a Select Menu component.
https://github.com/discordjs/discord-api-types/blob/3ff85eede4ad2954819dc9e76c6bdb4dc52ee57d/payloads/v9/channel.ts#L1159

**Include a reproducible code sample here, if possible:**
N/A

**Further details:**
The PR #209 mistakenly marks the property as optional in Select Menus. The PR refers to a PR made on the Discord API Docs which marks the `options` property as optional in a **general Message Component** object, not a Select Menu object.

**Comment by vladfrangu** [comment]
Feel free to submit a PR to revert that PR you mentioned if that's the case 😅🙏

**Comment by PikaDude** [comment]
> Feel free to submit a PR to revert that PR you mentioned if that's the case 😅🙏

done
