### ISSUE TITLE
Route for "Modify Current Member" is undocumented

### ISSUE THREAD

**Issue by BenjammingKirby** [discordjs/discord-api-types#260]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```ts
// Place your code here
```

**Further details:**

- Runtime:
  
  - Node.js version:
  - deno version:
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by ImRodry** [comment]
Uhm…?

**Comment by BenjammingKirby** [comment]
i guess it was a glitch #261 this is what i meant to open from the start, sorry
