### ISSUE TITLE
Route documentation inconsistent for "Modify Current Member"

### ISSUE THREAD

**Issue by BenjammingKirby** [discordjs/discord-api-types#261]
**Please describe the problem you are having in as much detail as possible:**
Seeing other functions like [guildVoiceState](https://github.com/discordjs/discord-api-types/blob/315ce3584917635b93a26123470f37a10bd8d846/rest/v9/index.ts#L736) and `user`
They have a default value of "@me" and the type is `Snowflake | @me` and the routes are mentioned
```ts
       /**
	 * Route for:
	 * - PATCH `/guilds/{guild.id}/voice-states/@me`
	 * - PATCH `/guilds/{guild.id}/voice-states/{user.id}`
	 */
	guildVoiceState(guildId: Snowflake, userId: Snowflake | '@me' = '@me') {
		return `/guilds/${guildId}/voice-states/${userId}` as const;
	},
 ```
However for the [`guildMember`](https://github.com/discordjs/discord-api-types/blob/315ce3584917635b93a26123470f37a10bd8d846/rest/v9/index.ts#L239) function, the type  for `userId` is just Snowflake, it doesn't have a default value and the [`@me`](https://discord.com/developers/docs/resources/guild#modify-current-member) is completely undocumented
shouldn't this be consistent?

**Comment by vladfrangu** [comment]
Do those endpoints exist? Do they work? The documentation doesn't list them afaik

**Comment by BenjammingKirby** [comment]
i saw the [modify current member](https://discord.com/developers/docs/resources/guild#modify-current-member) in the documentation
i am unsure if it works, let me try it out

**Comment by BenjammingKirby** [comment]
yep it works
also for [modify current user nick](https://discord.com/developers/docs/resources/guild#modify-current-user-nick)
> Deprecated in favor of Modify Current Member.
  which also isn't mentioned as deprecated unlike other methods i've seen such as channelThreads

**Comment by vladfrangu** [comment]
Heck, i didn't even notice that route was deprecated 👀 
Feel free to submit a PR to fix this :D

**Comment by BenjammingKirby** [comment]
sure, on it, do i also mention that `guildCurrentMemberNickname` is deprecated on the same pr?

**Comment by vladfrangu** [comment]
👍 Yes, just slap a `@deprecated Use guildCurrentMember instead`  on it! Also, make sure to update v8 too, if applicable

**Comment by BenjammingKirby** [comment]
checked for v8 too, the endpoint works
