### ISSUE TITLE
autocomplete field present for some reason

### ISSUE THREAD

**Issue by ghostdevv** [discordjs/discord-api-types#290]
**Please describe the problem you are having in as much detail as possible:**

I just migrated fully to discord-api-types in a package I am working on, and was wondering why `RESTPostAPIChatInputApplicationCommandsJSONBody` is typed as

```ts
export interface RESTPostAPIChatInputApplicationCommandsJSONBody extends RESTPostAPIBaseApplicationCommandsJSONBody {
    type?: ApplicationCommandType.ChatInput;
    /**
     * Whether this application command option should be autocompleted
     */
    autocomplete?: boolean;
    description: string;
}
```

it has autocomplete property and I am unsure as to why? Especially as when trying to look at the source in this repository it doesn't seem to have this, the above code block is taken from the installed version (running latest as of posting this)

**Further details:**

- Runtime:
  
  - Node.js version: 16
  - deno version: n/a
- Priority this issue should have – please be realistic and elaborate if possible:

Since autocomplete is typed as optional it's not a big deal (especially as it's internal code) but would like to get this typed properly asap of course

**Comment by vladfrangu** [comment]
Looks like you're on an outdated version, this has since been corrected and removed afaik 👀

**Comment by ghostdevv** [comment]
@vladfrangu that's odd :thinking: will double check this - might be a pnpm linking issue or something

**Comment by ghostdevv** [comment]
yep my bad was a updating issue! thanks!
