### ISSUE TITLE
`APIApplicationCommandOption#choices` has wrong type for `value`

### ISSUE THREAD

**Issue by suneettipirneni** [discordjs/discord-api-types#291]
**Please describe the problem you are having in as much detail as possible:**

The `value` type on an option choice is incorrect when setting the option to a `STRING` type for example.

**Include a reproducible code sample here, if possible:**

```ts
const data: APIApplicationCommandOption = {
    name: 'test',
    type: ApplicationCommandOptionType.String,
    choices: [
      {name: 'test', value: 'test'} // Type 'string' is not assignable to type 'number'
    ]
}; 
```

**Further details:**

- Runtime:
  
  - Node.js version: 16.10;0
- Priority this issue should have – please be realistic and elaborate if possible:
Medium

**Comment by vladfrangu** [comment]
Cannot reproduce 
![image](https://user-images.githubusercontent.com/17960496/148695286-6db0ef46-d5ea-4291-a52b-80cccf2a1ab4.png)

**Comment by suneettipirneni** [comment]
Figured out the issue, for some reason it gives that error if you don't provide a `description`.
