### ISSUE TITLE
Move from const enums

### ISSUE THREAD

**Issue by ghostdevv** [discordjs/discord-api-types#295]
**Is your feature request related to a problem? Please describe.**
I need to access one of the enums (`ApplicationCommandOptionType`) but do it dynamically, currently it's a const enum so you are unable to do that

**Describe the ideal solution**
It's made a non const enum

**Describe alternatives you've considered**
Copying and pasting the enum into my project (I will then have to make sure I constantly update this which works but isn't ideal)

**Additional context**
Would be worth doing this on discord.js itself if there aren't plans to fully use this package on djs

**Comment by vladfrangu** [comment]
What's the use case for this? Getting the PascalCase names? The reason these enums are const and will most likely stay that way is to inline their values in the compiled code 👀

**Comment by ghostdevv** [comment]
I need to convert a string type such as `INTEGER` to it's type number so I can send that off to the discord api @vladfrangu
the commands are dynamically imported and processed at runtime so it can't be done at compile time

I wonder how discord.js does it for non typescript users providing `INTEGER` (how it resolves that to it's type number to send to the api

**Comment by sylv** [comment]
I've also had this issue. NextJS uses the `isolatedModules` compiler option which doesn't allow const enums, causing our dashboard to have magical numbers thrown around when doing things like filtering and displaying channels, each one requiring comments explaining what its representing. It also prevents dynamic lists using [ts-enum-util](https://www.npmjs.com/package/ts-enum-util) for something like an option type dropdown, or using enums for validation with `@IsEnum` from [class-validator](npmjs.com/package/class-validator) 

For now I've just stuck with copy/pasting enums without `const` for validation and some dynamic lists or not using them at all for filtering and other static use cases with `isolatedModules` enabled, but it would be really nice if it just wasn't an issue to begin with.

**Comment by ghostdevv** [comment]
Would be great to do this for sure especially now that https://github.com/discordjs/discord.js/issues/7270 is done
