### ISSUE TITLE
Current sync status with Discord API Docs PRs

### ISSUE THREAD

**Issue by vladfrangu** [discordjs/discord-api-types#31]
~~A lot of PRs are (still) open in Discord's API Docs repository, and some features may arrive that we don't have the types for yet~~ Vlad from the future here: that isn't the case anymore
This issue is here just as a check list to make sure we are at least up to date with Discord

If any of these have been done already, let me know here, on Discord, and if not, feel free to either let us know here or make a PR!

<details>
<summary>Round 1</summary>

- [x] https://github.com/discord/discord-api-docs/pull/2118

- [x] https://github.com/discord/discord-api-docs/pull/1764

- [x] https://github.com/discord/discord-api-docs/pull/2155

- [x] https://github.com/discord/discord-api-docs/pull/2087 ?

- [ ] https://github.com/discord/discord-api-docs/pull/1762

- [x] https://github.com/discord/discord-api-docs/pull/1708

- [x] https://github.com/discord/discord-api-docs/pull/2044

- [x] ![image](https://user-images.githubusercontent.com/17960496/97698633-79354580-1ab1-11eb-97da-61acea388aa8.png)

- [x] https://github.com/discord/discord-api-docs/pull/2209 ?

- [x] https://github.com/discord/discord-api-docs/pull/2215

- [x] https://github.com/discord/discord-api-docs/pull/2214

</details>

<details open>
<summary>Round 2</summary>

- [x] Re-organize interactions structure because 1 file is NOT enough

- [ ] Consider re-organizing all REST files based on their methods? so we'd do /rest/interactions/\<method>.ts, where we define just that method's interfaces, respecting the current naming convention 

- [ ] Oauth2 types. Are they even accurate? Nobody knows. Need to shoot an eye at those again, esp with all the scopes... Lord spare me

- [x] https://github.com/discord/discord-api-docs/pull/1762

- [x] https://github.com/discord/discord-api-docs/commit/77c375643616246f23a84e5f63d9cf9776e9a164

- [x] https://github.com/discord/discord-api-docs/commit/eed60845ae6df3ed4c96b5ab520acd78adb0fb17

- [x] https://github.com/discord/discord-api-docs/commit/2c9f17887a8e5c95d48b93901f4543beda4c09be

- [x] https://github.com/discord/discord-api-docs/commit/0b2b84d94b9abd4688158edf0534dfdd062591b4

- [x] https://github.com/discord/discord-api-docs/commit/5afbad75892a907726ab47eea4d9bcbeabcdaa18

- [x] https://github.com/discord/discord-api-docs/pull/2855

- [x] https://github.com/discord/discord-api-docs/pull/2869

- [x] Boopable Noses - Soon™️ 

</details>

**Comment by vladfrangu** [comment]
Round 2! FIGHT

- [ ] Re-organize interactions structure because 1 file is NOT enough

- [ ] Consider re-organizing all REST files based on their methods? so we'd do /rest/interactions/<method>.ts, where we define just that method's interfaces, respecting the current naming convention 

- [ ] Oauth2 types. Are they even accurate? Nobody knows. Need to shoot an eye at those again, esp with all the scopes... Lord spare me

- [ ] https://github.com/discord/discord-api-docs/pull/1762

- [ ] https://github.com/discord/discord-api-docs/commit/77c375643616246f23a84e5f63d9cf9776e9a164

- [ ] https://github.com/discord/discord-api-docs/commit/eed60845ae6df3ed4c96b5ab520acd78adb0fb17

- [ ] https://github.com/discord/discord-api-docs/commit/2c9f17887a8e5c95d48b93901f4543beda4c09be

- [ ] https://github.com/discord/discord-api-docs/commit/0b2b84d94b9abd4688158edf0534dfdd062591b4

- [ ] https://github.com/discord/discord-api-docs/commit/5afbad75892a907726ab47eea4d9bcbeabcdaa18

- [ ] https://github.com/discord/discord-api-docs/pull/2855

- [ ] Boopable Noses - Soon™️

**Comment by advaith1** [comment]
> Re-organize interactions structure because 1 file is NOT enough

probably should wait until docs are updated & separated

**Comment by vladfrangu** [comment]
> > Re-organize interactions structure because 1 file is NOT enough
> 
> probably should wait until docs are updated & separated

This isn't really a need to wait for docs situation. And I doubt that'll happen soon, this is more of a comfort thing for us. My plan is to have a folder `_interactions` where I plop all enums in one file, all sent data in ine, all received data in another, etc

**Comment by advaith1** [comment]
ah, I meant like wait until slash commands and general interaction docs are separate and move those into separate files, that would probably make it cleaner
