### ISSUE TITLE
Type `ApplicationCommandType.User` is not assignable to `ContextMenuCommandType` after updating to 0.27.0

### ISSUE THREAD

**Issue by SuperchupuDev** [discordjs/discord-api-types#326]
**Please describe the problem you are having in as much detail as possible:**
I don't know if this is more of a builders issue, but it showed up when dependabot tried to update discord-api-types in my repo, and it showed this error:
![image](https://user-images.githubusercontent.com/53496941/153751941-2c33fe94-fd1a-433b-a092-8cbf7de4ec1a.png)
After looking at the builders source code, looks like `ContextMenuCommandType` should be working correctly, since it's defined as `ApplicationCommandType.User | ApplicationCommandType.Message`

**Include a reproducible code sample here, if possible:**

```ts
import { ContextMenuCommandBuilder } from '@discordjs/builders';
import { ApplicationCommandType } from 'discord-api-types';

export const data = new ContextMenuCommandBuilder().setName('Hi').setType(ApplicationCommandType.User);
```

**Further details:**

- Runtime:
  
  - Node.js version: 17.4.0
  - deno version:
- Priority this issue should have – please be realistic and elaborate if possible:
Medium

**Comment by vladfrangu** [comment]
This happens when you have a clash between discord-api-types versions! Builders uses 0.26.x, whereas you probably installed 0.27.0 and the enums don't match anymore 😅

Best bet is to wait for builders to update

**Comment by kyranet** [comment]
As a side note, you should import the types from `discord-api-types/v9`, bare exports aren't supported.

**Comment by SuperchupuDev** [comment]
> As a side note, you should import the types from `discord-api-types/v9`, bare imports aren't supported.

Will do, thanks 🙏

**Comment by vladfrangu** [comment]
Since this isn't an issue with discord-api-types, I will be closing this. For the future, if you want to define discord-api-types in your package.json, and use any other dependencies that depend on it too (like discord.js, discordjs/builders or discordjs/rest), you should set `discord-api-types` to `*` in package.json
