### ISSUE TITLE
Add support for Discord API v10

### ISSUE THREAD

**Issue by XEfnexX** [discordjs/discord-api-types#330]
**Is your feature request related to a problem? Please describe.**
It is the new stable API version from discord. New features will only be released at v10+

**Describe the ideal solution**
Switch from API v9 to  API v10

**Additional context**
API Release:  https://github.com/discord/discord-api-docs/discussions/4510

**Comment by XEfnexX** [comment]
I'm speed 😎

**Comment by ThunderDoesDev** [comment]
Has v10 been release yet as its not showing when install the npm?

**Comment by vladfrangu** [comment]
discord-api-types@next has it, and a full release will be done on Thursday

**Comment by ThunderDoesDev** [comment]
Okay
