### ISSUE TITLE
Wrong ATTACHMENT Application Command Option Type

### ISSUE THREAD

**Issue by sizumita** [discordjs/discord-api-types#375]
**Please describe the problem you are having in as much detail as possible:**

https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type
The Document says ATTACHMENT type's data is [attachment](https://discord.com/developers/docs/resources/channel#attachment-object) object but it's Snowflake in discord-api-types .

https://github.com/discordjs/discord-api-types/blob/f70298811242d946cee01b112c34382f0e54cb78/payloads/v10/_interactions/_applicationCommands/_chatInput/attachment.ts#L8-L11

**Include a reproducible code sample here, if possible:**

```ts
// Place your code here
```

**Further details:**

- Runtime:
  
  - Node.js version:
  - deno version:
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by vladfrangu** [comment]
The actual data you receive is just the id of the attachment, which you need to map from the resolved field. If that's wrong please provide raw API data for it and we'll fix it

**Comment by sizumita** [comment]
It certainly was. 🙏  I guess I was wrong. Thanks for the reply.
