### ISSUE TITLE
Enable ApplicationCommandOptionType Typings As Human Readable

### ISSUE THREAD

**Issue by calebcgates** [discordjs/discord-api-types#387]
There are many Application Command input variable types ex 3=string, 10=number
We should add human readable typings similar to the ApplicationCommandTypes

```
/**
 * https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-types
 */
export declare enum ApplicationCommandType {
    ChatInput = 1,
    User = 2,
    Message = 3
}

commandType = ApplicationCommandType.ChatInput;
```

A good solution might look like
```
/**
 * https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-options-types
 */
export declare enum ApplicationCommandOptionType {
SUB_COMMAND = 1,
SUB_COMMAND_GROUP = 2,
STRING = 3,
INTEGER = 4,
BOOLEAN  = 5,
USER = 6,
CHANNEL = 7,
ROLE = 8,
MENTIONABLE = 9,
NUMBER = 10,
ATTACHMENT = 11
}
```

I'm not entirely sure what file this should be exported from so I'm creating a request instead of a pull request.

**Comment by vladfrangu** [comment]
I'm confused, is it not `ApplicationCommandOptionType` what you need?

**Comment by calebcgates** [comment]
Lol, Yes actually. 

I couldn't find "it" so I wrote this post, suggested the logical name, and never thought to search for that specific name in the repo.  

Thanks for confirming
