### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by MARCROCK22** [discordjs/discord-api-types#456]
https://github.com/discordjs/discord-api-types/blob/db9938826736a9f864521cf7a56f48f206ccffba/gateway/v10.ts#L520
as you can see here ( https://discord.com/developers/docs/topics/gateway#guild-create-guild-create-extra-fields ) the GUILD_CREATE event have extra fields, all good with GatewayGuildCreateDispatchData, but GatewayGuildCreateDispatch has an issue

**Comment by vladfrangu** [comment]
Feel free to open a PR to fix this
