### ISSUE TITLE
Missing some thread listing related REST types

### ISSUE THREAD

**Issue by paperdave** [discordjs/discord-api-types#526]
I'm looking for the type information for the following rest routes and it seems they are not present:

- [`GET /channels/{channel.id}/threads/archived/public`](https://discord.com/developers/docs/resources/channel#list-public-archived-threads)
- [`GET /channels/{channel.id}/threads/archived/public`](https://discord.com/developers/docs/resources/channel#list-private-archived-threads)
- [`GET /channels/{channel.id}/users/@me/threads/archived/private`](https://discord.com/developers/docs/resources/channel#list-joined-private-archived-threads)

**Comment by vladfrangu** [comment]
> * [`GET /channels/{channel.id}/threads/archived/public`](https://discord.com/developers/docs/resources/channel#list-public-archived-threads)

Seems like we are missing an interface export for this

> * [`GET /channels/{channel.id}/threads/archived/public`](https://discord.com/developers/docs/resources/channel#list-private-archived-threads)

Seems like we are also missing an interface export for this

> * [`GET /channels/{channel.id}/users/@me/threads/archived/private`](https://discord.com/developers/docs/resources/channel#list-joined-private-archived-threads)

Type is `RESTGetAPIChannelUsersThreadsArchivedResult`

---

Feel free to open a PR for the missing ones if you want!

**Comment by RedGuy12** [comment]
I think `[GET /channels/{channel.id}/threads/archived/public](https://discord.com/developers/docs/resources/channel#list-public-archived-threads)` and `[GET /channels/{channel.id}/threads/archived/public](https://discord.com/developers/docs/resources/channel#list-private-archived-threads)` are also `RESTGetAPIChannelUsersThreadsArchivedResult` - the docs for all three say they only have `threads`, `members`, and `has_more`.
