### ISSUE TITLE
Bring back const enums

### ISSUE THREAD

**Issue by taralx** [discordjs/discord-api-types#533]
History: https://github.com/discordjs/discord-api-types/issues/295

So there *was* a transpilation bug (https://github.com/microsoft/TypeScript/issues/40499) that some people ran into, but that was fixed in Typescript 4.2. It should be possible to set [`preserveConstEnums`](https://www.typescriptlang.org/tsconfig#preserveConstEnums) and get the best of both worlds. I wouldn't be so bothered except my bundle size (via parcel) goes from 3k to 27k because it pulls in the whole big chunk for just a few numbers.

**Comment by taralx** [comment]
It doesn't? https://www.typescriptlang.org/play?preserveConstEnums=true#code/MYewdgzgLgBApmArgWxgCTgG0yGBvAKBmJgEEYBeGARgIF8Cg

**Comment by vladfrangu** [comment]
`const enums` have been very much a pain point in the library (and in the TypeScript ecosystem as a whole).

> Read more: https://github.com/Microsoft/TypeScript/issues/30590

![image](https://user-images.githubusercontent.com/17960496/180147273-074cfd5d-b5bb-468c-a4ea-ee98d009b36a.png)

As such, we will not bring them back. I'd be more worried why parcel or whatever bundler you use doesn't treeshake properly (is this our fault? Is it something else?)

Feel free to open an issue (or even a pull request) if treeshaking fails, and a repository to test it with, and we'll take a look :D

**Comment by taralx** [comment]
That's fair. Thank you for the detailed response.
