### ISSUE TITLE
Adding `Search` to the website

### ISSUE THREAD

**Issue by MeXi-001** [discordjs/discord-api-types#538]
**Is your feature request related to a problem? Please describe.**
Sometimes it can be difficult to find the types on the website

**Describe the ideal solution**
In my opinion, I think that there should be a search bar so we can search for the Types on the website

**Describe alternatives you've considered**
`no response`

**Additional context**
`no response`

**Comment by vladfrangu** [comment]
To quote myself from the Discord server (message https://canary.discord.com/channels/222078108977594368/941291502372552735/978783198047793192)

![Discord Canary - 2022-07-22 at 15 38 40@2x](https://user-images.githubusercontent.com/17960496/180440880-109df01f-e123-4e39-9bd7-46c44ebb9ae2.png)

**Comment by vladfrangu** [comment]
Search is (finally) added and fully operational. Have fun! Also, it uses contextual searching so switch between versions if you wanna find something in a specific version
