### ISSUE TITLE
Missing `total_message_sent` field on APIThreadChannel

### ISSUE THREAD

**Issue by KhafraDev** [discordjs/discord-api-types#553]
**Please describe the problem you are having in as much detail as possible:**

https://discord.com/channels/222078108977594368/1005167313877741588

**Include a reproducible code sample here, if possible:**

```ts
declare const channel: import('discord-api-types/v10').APIThreadChannel
channel.total_message_sent
```

**Further details:**

- Runtime:
  
  - Node.js version: n/a
  - deno version:
- Priority this issue should have – please be realistic and elaborate if possible: low

**Comment by vladfrangu** [comment]
And what version of -types are you on?

**Comment by KhafraDev** [comment]
updating fixed it
