### ISSUE TITLE
Importing into typescript project not working with bun

### ISSUE THREAD

**Issue by Susul-1312** [discordjs/discord-api-types#562]
**Please describe the problem you are having in as much detail as possible:**
When trying to import the GatewayIntentBits into a project, when running it with bun, the following error is displayed:
```
$ bun run src/lib/discord/bot.ts
[0.89ms] ".env"


error: Could not resolve: "discord-api-types/gateway". Maybe you need to "bun install"?

import { GatewayIntentBits } from "discord-api-types/gateway";
                                  ^
```
I have run bun install discord-api-types

A similar error is displayed with "discord-api-types/v10" and just "discord-api-types"

**Include a reproducible code sample here, if possible:**

```ts
import { GatewayIntentBits } from "discord-api-types/gateway";
```

**Further details:**

- Runtime: bun 0.1.8
  
  - Node.js version:
  - deno version:
- Priority this issue should have – please be realistic and elaborate if possible: Medium, since while this is a complete failture, bun is a new runtime

**Comment by Jiralite** [comment]
Is this actually a discord-api-types issue? What makes you so sure?

> Priority this issue should have – please be realistic and elaborate if possible: Medium, since while this is a complete failture, bun is a new runtime

This should be the lowest of the low - Bun is not even stable architecture.

**Comment by Susul-1312** [comment]
I can import other libraries just fine, which is why I assume its an issue with discord-api-types

**Comment by Jiralite** [comment]
I just installed Bun and I can't reproduce this.

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/33201955/184255536-db8940ce-0663-4c83-9c72-9ae36680dc2b.png">

**Comment by vladfrangu** [comment]
I just installed bun and also cannot reproduce your issue. 
![Code - Insiders - 2022-08-12 at 12 43 29@2x](https://user-images.githubusercontent.com/17960496/184328998-aa12c2e7-ef5c-406c-bca4-aa8b4bd93d77.png)

**Comment by Susul-1312** [comment]
I have ultimately found a workaround: manually cloning the files from github
