### ISSUE TITLE
Union type for data leads to an error

### ISSUE THREAD

**Issue by Syjalo** [discordjs/discord-api-types#573]
**Please describe the problem you are having in as much detail as possible:**
Type of `APIButtonComponent` has no `custom_id` property because the union type is used. It should be an interface extending the types. Maybe this is not the only type that has the same issue.

**Include a reproducible code sample here, if possible:**

```ts
let button!: APIButtonComponent;
button.custom_id; // Property 'custom_id' does not exist on type 'APIButtonComponentWithURL'.
```

`@discordjs/builders`:
```ts
new ButtonBuilder().data.custom_id; // Property 'custom_id' does not exist on type 'Partial<APIButtonComponentWithURL>'.
```

- Runtime:
  
  - Node.js version: v16.17.0
- Priority this issue should have: Medium

**Comment by vladfrangu** [comment]
This is no bug but rather strict typings making it safer in your code

If you know your button is never a link one, use the APIButtonComponentWithCustomId type. Otherwise, assert it based on the component.style property

**Comment by Syjalo** [comment]
Ok, thank you
