### ISSUE TITLE
`GuildChannelType` does not include category channels

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord-api-types#577]
**Please describe the problem you are having in as much detail as possible:**
`GuildChannelType` does not include category channels:

https://github.com/discordjs/discord-api-types/blob/04b3a7f066bd715897fa5eadb940b926f317ecc3/payloads/v10/channel.ts#L42-L56

**Include a reproducible code sample here, if possible:**

```ts
import { ChannelType, GuildChannelType } from "discord-api-types/v10";

declare const guildChannelType: GuildChannelType;

if (ChannelType.GuildCategory === guildChannelType) {
  // This condition will always return 'false'
}
```

**Further details:**

- Runtime:
  
  - Node.js version: 18.8.0
  - deno version: N/A
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Comment by harishfalco** [comment]
Greetings, @Jiralite    I'm new to contributing to open-source, I'd want to fix this problem. Give it to me, if possible.

**Comment by ImRodry** [comment]
you don't need authorization to make a PR, you just have to open it
