### ISSUE TITLE
suggestion: Add Deno support

### ISSUE THREAD

**Issue by DjDeveloperr** [discordjs/discord-api-types#59]
Hi!

After seeing comment in Pull Request in Discord API Docs repo for adding Deno support (https://github.com/discord/discord-api-docs/pull/2401#issuecomment-750946151), I decided to try this out.

From what I know, only import/export style has changed in Deno which makes this incompatible, which does not have anything like `index.js/ts` file and always requires extension of file to be in import.

I've made a script which goes through all files and makes imports/exports compatible with Deno, https://github.com/DjDeveloperr/denoify-dapi-types. There's even a working GitHub action which deploys on `deno` branch on every push. 
You can see live version on my fork of this repo, https://github.com/DjDeveloperr/discord-api-types.

I have tested, those auto-generated types do work with Deno 😄

**Comment by advaith1** [comment]
The modified version should be compatible with both node and deno, right? Can't we just add `/index.ts` to the imports in the main branch to have a simple version compatible with both?

**Comment by DjDeveloperr** [comment]
I'm pretty sure if adding `.ts` in imports is incompatible with TypeScript (Node).
![image](https://user-images.githubusercontent.com/43033058/103132032-2cdd3f00-46c9-11eb-845d-f86c189955b7.png)

**Comment by iCrawl** [comment]
https://github.com/microsoft/TypeScript/issues/37582

**Comment by vladfrangu** [comment]
I mean, personally, I'm willing to create a CD that deploys to a `deno` branch for the time being, fast enough! What do you think, @iCrawl, @kyranet?

**Comment by kyranet** [comment]
I personally have no issue with that, the question is... how are we going to transform the imports to support Deno?
