### ISSUE TITLE
Cannot use RESTError

### ISSUE THREAD

**Issue by grarich** [discordjs/discord-api-types#599]
Cannot import and use `RESTError` 

```ts
import { RESTError } from 'discord-api-types/v10';
```

- Runtime:
  - Node.js version: v16.14.2

**Comment by vladfrangu** [comment]
What's your discord-api-types version you're using?

**Comment by grarich** [comment]
im using v0.35.0.

**Comment by grarich** [comment]
Oh, the version was old.
Thank you.
