### ISSUE TITLE
FormattingPatterns.SlashCommand no longer matches official documentation example

### ISSUE THREAD

**Issue by kevinlul** [discordjs/discord-api-types#613]
### Issue description

In #597, FormattingPatterns.SlashCommand was updated.

In [official documentation](https://discord.com/developers/docs/reference#message-formatting), Discord provides `</airhorn:816437322781949972>` as an example. This used to match before this change but now fails to match.

### Code sample

```typescript
"</airhorn:816437322781949972>".match(/<\/(?<fullName>(?<name>[-_\p{Letter}\p{Number}\p{sc=Deva}\p{sc=Thai}]{1,32})(?: (?<subcommandOrGroup>[-_\p{Letter}\p{Number}\p{sc=Deva}\p{sc=Thai}]{1,32}))?(?: (?<subcommand>[-_\p{Letter}\p{Number}\p{sc=Deva}\p{sc=Thai}]{1,32}))?):(?<id>\d{17,20})>/)
// null
```
```typescript
"</airhorn:816437322781949972>".match(FormattingPatterns.SlashCommand)
// null
```

### Package version

0.37.14

### Runtime

Node.js

### Runtime version

v16.13.2 typescript@4.6.4

### Priority this issue should have

Medium (should be fixed soon)

**Comment by Jiralite** [comment]
That is not the correct regular expression. You are missing the flag.

**Comment by kevinlul** [comment]
I see the problem now, my apologies.
