### ISSUE TITLE
Documentation broken.... like litreally....

### ISSUE THREAD

**Issue by migue802** [discordjs/discord-api-types#708]
### Issue description

1. Open https://discord-api-types.dev/api
2. It broken 😞 (it only shows [GatewayURLQuery](https://discord-api-types.dev/api/interface/GatewayURLQuery) interface only)

### Package version

Latest, it's production documentation

### Runtime

Other / Browser

### Runtime version

Not specified/Latest

### Priority this issue should have

Medium (should be fixed soon)

**Comment by migue802** [comment]
Pics just in case needed
![image](https://user-images.githubusercontent.com/54627022/217543214-a147ff18-d76d-456d-a155-5fcffaff247e.png)

**Comment by vladfrangu** [comment]
A dependency update broke it :dead: It's been rolled back and it works now
