### ISSUE TITLE
APIRole - Missing Type - APIRole["permissions_new"]

### ISSUE THREAD

**Issue by LKNSI** [discordjs/discord-api-types#734]
### Issue description

~~Hi!~~

~~Feel free to close this if I am making a mistake, but for APIRole (And every other type that makes use of it) may be missing a new property "permissions_new".~~

~~Here's the latest response from the guild role endpoint at `/guilds/x/roles`~~

```JSON
{
        "id": "x",
        "name": "x",
        "description": null,
        "permissions": 104320834,
        "position": 18,
        "color": 16732416,
        "hoist": true,
        "managed": false,
        "mentionable": true,
        "icon": "x",
        "unicode_emoji": null,
        "flags": 0,
        "permissions_new": "2171210288962"
    },
```

### Package version

0.37.36

### Runtime

Node.js

### Runtime version

v18.12.1

### Priority this issue should have

Medium (should be fixed soon)~~

**Comment by vladfrangu** [comment]
Holy heck this is an outdated API field! You might be on API v6 or v7, as v8 and onwards has permissions as strings from the get-go. You should really update!

**Comment by Jiralite** [comment]
Read more here: https://discord.com/developers/docs/change-log#api-and-gateway-v8

**Comment by LKNSI** [comment]
> Holy heck this is an outdated API field! You might be on API v6 or v7, as v8 and onwards has permissions as strings from the get-go. You should really update!

May be VSCode resolving to the wrong module (or an outdated version) but I'm up to date AFAICT

Is 0.37.36 outdated heavily? 

![image](https://user-images.githubusercontent.com/3456318/225738827-fecf914a-11bc-4ecb-8912-05600b1a4c9d.png)

**Comment by LKNSI** [comment]
Completely my fault, forgot to add /v10 to the route and was misattributing it to discord-types.
