### ISSUE TITLE
`export const enum` -> `export enum`

### ISSUE THREAD

**Issue by ayntee** [discordjs/discord-api-types#74]
When the `const` keyword is prefixed before the declaration of an enum, the enum itself is obliterated during the compilation, this may produce errors if the enum is used as a value in a program.

For instance, we declare two enums, one with `const` and the other without `const`:

```typescript
export enum Test {}

export const enum Test2 {}
```

The aforementioned code produces the following code:

```typescript
export var Test;
(function (Test) {
})(Test || (Test = {}));

// "Test2" enum is entirely erased from the compiled code.
```

**Comment by iCrawl** [comment]
Yes, we know how const Enums work.

What's your issue with how this library uses them?

**Comment by ayntee** [comment]
> Yes, we know how const Enums work.
> 
> What's your issue with how this library uses them?

For example, if a program is using the enum as a value, this would produce errors.

**Comment by iCrawl** [comment]
Thats not how const Enums work.

Your example in the first post is a bad one, because you don't have any values. 

```js
export const enum Test2 {
  Test
}

const a = {
  b: Test2.Test
}
```

Results in:

```js
const a = {
    b: 0 /* Test */
};
export {};
```

So I ask again, what is the issue you have with how we use them?

**Comment by ayntee** [comment]
> ```js
> const a = {
>     b: 0 /* Test */
> };
> export {};
> ```
