### ISSUE TITLE
Route extension typings

### ISSUE THREAD

**Issue by TAEMBO** [discordjs/discord-api-types#866]
### Issue description

`CDNRoutes` on API v10 has functions that return routes where most of them take a file format as a parameter (png, jpeg, etc.). The downside that this has caused is that the typings for them result in their return types being large template literal union types - one for each format possible. This not only makes it harder for those using these functions to quickly comprehend what will actually be returned from a given function, however it also from what I can see makes more work for those maintaining the typings for CDNRoutes - having to make sure the comment, allowed formats, and union return types are all in sync. I think this can be done better.

My proposal is to utilize generics for each of these CDNRoutes functions, which drastically reduces the amount of actual content needed to complete and maintain the typings for each function, and also makes for a smarter template literal return type which mutates based on the format specified - thus making for a better experience for those using these functions from my point of view.

I'm more than welcome to hearing others' thoughts on this and opening a PR assuming there's no issues with this that others are able to point out.

As a side note, the CDNRoutes `storePageAsset` function is implemented incorrectly. Its own [comments](https://github.com/discordjs/discord-api-types/blob/main/rest/v10/index.ts#L1113 ) as well as Discord's [documentation](https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints) specify that it supports the PNG, JPEG, and WebP extensions, yet it's written to only return a PNG extension with no option to specify which available one to use.

### Code sample

```typescript
// Current behavior
import { CDNRoutes, ImageFormat } from "discord-api-types/v10";

CDNRoutes.emoji("id", ImageFormat.PNG);
// Return value typed as `/emojis/${string}.jpeg` | `/emojis/${string}.png` | `/emojis/${string}.webp` | `/emojis/${string}.gif`



// Ideal behavior
import { CDNRoutes, ImageFormat } from "discord-api-types/v10";

CDNRoutes.emoji("id", ImageFormat.PNG);
// Return value typed as `/emojis/${string}.png`
```

### Package version

0.37.61

### Runtime

Node.js

### Runtime version

v18.17.0 (TypeScript v5.2.2)

### Priority this issue should have

Low (slightly annoying)

**Comment by vladfrangu** [comment]
You're free to open a PR for this, as long as it still keeps the strict type for the formats and only allows actually allowed types 👀

**Comment by TAEMBO** [comment]
Thank you! I noticed the strict format types that were set for each of them when digging into this and I'll be sure to keep those same boundaries.
