### ISSUE TITLE
Workflow for dev releases is failing

### ISSUE THREAD

**Issue by SuperchupuDev** [discordjs/discord-api-types#883]
### Issue description

See https://github.com/discordjs/discord-api-types/actions/runs/8145610559/job/22262268262

[According to npm](https://www.npmjs.com/package/discord-api-types?activeTab=versions), the last successful @-next release was `0.37.36-next.0d47c69.1677334692`, which shows it's not a one-off issue and it's been happening for a while

### Package version

main

### Runtime

Other / Browser

### Runtime version

N/A

### Priority this issue should have

Medium (should be fixed soon)

**Comment by vladfrangu** [comment]
I'm aware now, fixing it right now XD

**Comment by vladfrangu** [comment]
Fixed
