### ISSUE TITLE
fix: revert Snowflake type

### ISSUE THREAD

**Issue by Favna** [discordjs/discord-api-types#97]
**Please describe the problem you are having in as much detail as possible:**

The ``Snowflake = `${bigint}` `` structure is quite annoying

Also just posting this coz @vladfrangu asked on sapphire discord

**Include a reproducible code sample here, if possible:**

N.A.

```ts
// Place your code here
```

**Further details:**

- Runtime:
  
  - Node.js version: N.A.
  - deno version: N.A.
- Priority this issue should have – please be realistic and elaborate if possible: medium

**Comment by vladfrangu** [comment]
TL;DR. Just cast it, since it's the correct way to ensure it's an ID. The structure won't leave
